services:
  - type: web
    name: web-security-scanner
    env: python
    buildCommand: pip install -r requirements_web.txt
    startCommand: python web_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 